version: "3.8"

services:
    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        env_file: .env
        environment:
            - MYSQL_DATABASE=wordpress
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        env_file: .env
        environment:
            - PMA_HOST=db
            - PMA_ARBITRARY=1
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
        ports:
            - "8081:80"
        networks:
            - app-network

    wordpress:
        depends_on:
            - db
        image: wordpress:${WORDPRESS_VERSION}
        container_name: wordpress
        restart: unless-stopped
        env_file: .env
        environment:
            - WORDPRESS_DB_HOST=db:3306
            - WORDPRESS_DB_USER=$MYSQL_USER
            - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
            - WORDPRESS_DB_NAME=wordpress
            - WORDPRESS_DEBUG=1
            - |
                WORDPRESS_CONFIG_EXTRA=
                define( 'SAVEQUERIES', true );
                define( 'WP_AUTO_UPDATE_CORE', false );

        volumes:
            - wordpress:/var/www/html
            - ./wp-content/theme/${THEME_SLUG}:/var/www/html/wp-content/themes/${THEME_SLUG}
            - ./wp-content/plugins:/var/www/html/wp-content/plugins
            - ./.docker/php/uploads.conf:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - app-network

    webserver:
        depends_on:
            - wordpress
        image: nginx:1.19.4-alpine
        container_name: webserver
        restart: unless-stopped
        env_file: .env
        environment:
            - NGINX_HOST=$LOCAL_URL
        ports:
            - "80:80"
        volumes:
            - wordpress:/var/www/html
            - ./wp-content/theme/${THEME_SLUG}:/var/www/html/wp-content/themes/${THEME_SLUG}
            - ./wp-content/plugins:/var/www/html/wp-content/plugins
            - ./.docker/nginx-templates:/etc/nginx/templates
            - ./.docker/php/uploads.conf:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - app-network

volumes:
    wordpress:
    dbdata:

networks:
    app-network:
        driver: bridge
